# travis configuration for ProfiWiki
# could be any language since we are using docker
language: java

sudo: required

services:
  - docker

dist: bionic

env:
  COMPOSE_VERSION: 1.23.2

before_install:
  # Docker Compose Install
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  # install three different mediawikis using docker
  - ./mw1_31_1  -p 8081
  - ./mw1_30_1  -p 8082
  - mw1_27_5  -p 8083
  # install mediawiki 1.31.1 locally
  - ./mw1_31_1  -p 8080 -l

script:
  # testall four mediawikis
  - testinstall 8081
  - testinstall 8082
  - testinstall 8083
  - testinstall 8084

after_script:
  - docker-compose stop
  - docker-compose rm -f
